echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
#echo "I am from batch-33 and learning git/github to improve my skills"
#echo "Good morning everyone, I am Shubham and I am learning Linux"